In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
test_df = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")

In [3]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
train_df["text"][45]

'I gained 3 followers in the last week. You? Know your stats and grow with http://t.co/TIyUliF5c6'

In [5]:
train_df = train_df.drop(["id","keyword","location"],axis =1)

In [6]:
train_df.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [7]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [8]:
test_df = test_df.drop(["id","keyword","location"],axis =1)

In [9]:
test_df.head()

text
0                 Just happened a terrible car crash
1  Heard about #earthquake is different cities, s...
2  there is a forest fire at spot pond, geese are...
3           Apocalypse lighting. #Spokane #wildfires
4      Typhoon Soudelor kills 28 in China and Taiwan

In [10]:
import spacy

nlp = spacy.load("en_core_web_sm")
spacy_stopwords = nlp.Defaults.stop_words

def remove_stopwords(text):
    tokens = nlp(text)
    filtered_tokens = [token.text for token in tokens if not token.is_stop]
    return " ".join(filtered_tokens)

train_df['text'] = train_df['text'].apply(remove_stopwords)
test_df['text'] = test_df['text'].apply(remove_stopwords)


In [11]:
train_df

text  target
0               Deeds Reason # earthquake ALLAH Forgive       1
1               Forest fire near La Ronge Sask . Canada       1
2     residents asked ' shelter place ' notified off...       1
3     13,000 people receive # wildfires evacuation o...       1
4     got sent photo Ruby # Alaska smoke # wildfires...       1
...                                                 ...     ...
7608  giant cranes holding bridge collapse nearby ho...       1
7609  @aria_ahrary @TheTawniest control wild fires C...       1
7610  M1.94 [ 01:04 UTC]?5 km S Volcano Hawaii . htt...       1
7611  Police investigating e - bike collided car Lit...       1
7612  Latest : Homes Razed Northern California Wildf...       1

[7613 rows x 2 columns]

In [12]:
"""import pandas as pd
import nltk
from nltk.tokenize import TweetTokenizer

# Instantiate the tokenizer
tokenizer = TweetTokenizer()

# Define a function to tokenize a tweet
def tokenize_tweet(tweet):
    return tokenizer.tokenize(tweet)

# Apply the function to every row in the DataFrame
train_df['text'] = train_df['text'].apply(tokenize_tweet)
test_df['text'] = test_df['text'].apply(tokenize_tweet)


"""

"import pandas as pd\nimport nltk\nfrom nltk.tokenize import TweetTokenizer\n\n# Instantiate the tokenizer\ntokenizer = TweetTokenizer()\n\n# Define a function to tokenize a tweet\ndef tokenize_tweet(tweet):\n    return tokenizer.tokenize(tweet)\n\n# Apply the function to every row in the DataFrame\ntrain_df['text'] = train_df['text'].apply(tokenize_tweet)\ntest_df['text'] = test_df['text'].apply(tokenize_tweet)\n\n\n"

In [13]:
train_df["text"] = train_df["text"].str.lower()
test_df["text"] = test_df["text"].str.lower()

In [14]:
train_df.head()

text  target
0            deeds reason # earthquake allah forgive       1
1            forest fire near la ronge sask . canada       1
2  residents asked ' shelter place ' notified off...       1
3  13,000 people receive # wildfires evacuation o...       1
4  got sent photo ruby # alaska smoke # wildfires...       1

In [15]:
import re
def remove_html_tags(text):
    pattern = re.compile("<.*?>")
    return pattern .sub(r' ',text )

In [16]:
train_df["text"] = train_df["text"].apply(remove_html_tags)
test_df["text"] = test_df["text"].apply(remove_html_tags)


In [17]:
train_df.sample(10)

text  target
3852  * new * snap tools black baseball hat / cap si...       0
5744  @teamvodg discovered @nickcannon \n  listen / ...       0
4378  governor weighs parole california school bus h...       1
1307  kanger coils - burning fast ? /r / vaping101 h...       0
334       armageddon averted el patron \n # ultimalucha       0
2183  debris found reunion island comes mh370 : mala...       1
251   u.s national park services tonto national fore...       1
5891  watch airport swallowed sandstorm minute http:...       1
6282  finna storm . fuck boutta start hurting like m...       0
2224  audio : 16 business owners share differently p...       0

In [18]:

def remove_urls(text):
    pattern = re.compile(r"https?://\S+|www\.\S+")
    return pattern.sub(r'',text)

In [19]:
train_df["text"] = train_df["text"].apply(remove_urls)
test_df["text"] = test_df["text"].apply(remove_urls)


In [20]:
train_df.sample(10)

text  target
4839  @mnpdnashville @montalbanony sadly suicide cop...       1
1265  probably stay away hot glue guns .. burned fin...       0
5198  god @mets cocky right love . uribe obliterated...       0
6265  kesabaran membuahkan hasil indah pada saat tep...       1
7266  pawsox owners public return whirlwind trip dur...       0
5970    @kamkasteiiano @bluntedjayt fucking screaming !       0
6730  oun continues severe thunderstorm warning okla...       1
6289  # nasa announced massive # solar storm headed ...       1
917   marlon williams & gt ; elvis presley & gt ; ma...       0
7576                                           wrecked        0

In [21]:
train_df["target"].value_counts(normalize = True)

0    0.57034
1    0.42966
Name: target, dtype: float64

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [23]:
t = Tokenizer(oov_token="UNK")
t.fit_on_texts(train_df["text"]) # create undex for each word sometimes index genearation might be different from others


vocab_size = len(t.word_index)+1 # why should add 1 because when we do padding we will introduce 0 
print(vocab_size)

17142


In [24]:
# integer encode the documents 
encoded_docs = t.texts_to_sequences(train_df["text"]) # transformations of senetences
print(train_df["text"].head())


0              deeds reason # earthquake allah forgive
1              forest fire near la ronge sask . canada
2    residents asked ' shelter place ' notified off...
3    13,000 people receive # wildfires evacuation o...
4    got sent photo ruby # alaska smoke # wildfires...
Name: text, dtype: object


In [25]:
# numerical representation of first sentence
print(encoded_docs[0])

[4306, 691, 135, 1402, 4307]


In [26]:
test_encoded_docs = t.texts_to_sequences(test_df["text"])

In [27]:
max_length = 100
padded_docs = pad_sequences(encoded_docs,maxlen=max_length,padding ="post")
test_padded_docs = pad_sequences(test_encoded_docs,maxlen=max_length,padding ="post")
print(padded_docs)
type(padded_docs)

[[4306  691  135 ...    0    0    0]
 [  85    5  118 ...    0    0    0]
 [1525 1403    2 ...    0    0    0]
 ...
 [2558 2163  552 ...    0    0    0]
 [  14  946  437 ...    0    0    0]
 [ 102   97  406 ...    0    0    0]]


numpy.ndarray

In [28]:
type(train_df["text"])

pandas.core.series.Series

In [29]:
text = np.array(train_df["target"])

In [30]:
X = padded_docs
y = text

In [31]:
test_padded_docs

array([[ 734, 1727,   46, ...,    0,    0,    0],
       [ 340,  135,  998, ...,    0,    0,    0],
       [  85,    5,  653, ...,    0,    0,    0],
       ...,
       [ 784,  527,  224, ...,    0,    0,    0],
       [5971,  450,  301, ...,    0,    0,    0],
       [5662, 2567, 1393, ...,    0,    0,    0]], dtype=int32)

In [32]:
from sklearn.model_selection import train_test_split
  

  

X_train, X_test,y_train, y_test = train_test_split(X,y ,
                                   random_state=10, 
                                   test_size=0.30, 
                                   shuffle=True)

In [33]:
def get_glove_embeddings_from_file(path):
    glove = open(path,"r",encoding = "utf-8")
    glove_dict ={}
    for line in glove:
        values = line.split()
        word =values[0]
        word_vec = np.asarray(values[1:])
        glove_dict[word] = word_vec
    glove.close()
    return glove_dict

In [34]:
#glove_dict = get_glove_embeddings_from_file(path="/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.100d.txt")

In [35]:
#glove_dict1 = get_glove_embeddings_from_file(path="/content/gdrive/MyDrive/glove.6B.200d.txt")

In [36]:
glove_dict2 = get_glove_embeddings_from_file(path="/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.50d.txt")

In [37]:
glove_dict2["the"]

array(['0.418', '0.24968', '-0.41242', '0.1217', '0.34527', '-0.044457',
       '-0.49688', '-0.17862', '-0.00066023', '-0.6566', '0.27843',
       '-0.14767', '-0.55677', '0.14658', '-0.0095095', '0.011658',
       '0.10204', '-0.12792', '-0.8443', '-0.12181', '-0.016801',
       '-0.33279', '-0.1552', '-0.23131', '-0.19181', '-1.8823',
       '-0.76746', '0.099051', '-0.42125', '-0.19526', '4.0071',
       '-0.18594', '-0.52287', '-0.31681', '0.00059213', '0.0074449',
       '0.17778', '-0.15897', '0.012041', '-0.054223', '-0.29871',
       '-0.15749', '-0.34758', '-0.045637', '-0.44251', '0.18785',
       '0.0027849', '-0.18411', '-0.11514', '-0.78581'], dtype='<U11')

In [38]:
def get_glove_embeddings(tokenizer,glove_dict,word_length):
    vocab = len(tokenizer.word_index)+1
    embedding_matrix = np.zeros((vocab,word_length))
    for word , i in tokenizer.word_index.items():
        embedding_vector = glove_dict.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector
    return embedding_matrix

In [39]:
embedding_matrix=get_glove_embeddings(tokenizer = t,glove_dict = glove_dict2,word_length=50)

In [40]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,Flatten,BatchNormalization,LayerNormalization, Bidirectional,Dropout,LSTM,GRU
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow import keras


In [119]:
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
es = EarlyStopping(monitor='accuracy', patience=3)
callbacks_list = [checkpoint, es]

In [126]:
def build_glove_embeddings_text_model(embedding_matrix,vocab,input_length,word_length):
    model = Sequential()
    model.add(Embedding(vocab,word_length,input_length=input_length,weights=[embedding_matrix],trainable =False))
    
    model.add(Bidirectional(GRU(256,return_sequences=True)))
    
    model.add(Bidirectional(GRU(256,return_sequences=True)))
    
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    
    model.add(Bidirectional(GRU(128,return_sequences=True)))

    model.add(Bidirectional(GRU(128,return_sequences=True)))
    
    model.add(Bidirectional(GRU(64,return_sequences=True)))
    
    model.add(Bidirectional(GRU(64,return_sequences=True)))
    
    model.add(Bidirectional(GRU(64,return_sequences=True)))
    
    model.add(Bidirectional(GRU(64,return_sequences=True)))
    
    model.add(Bidirectional(GRU(32,return_sequences=True)))
    
    model.add(Bidirectional(GRU(32,return_sequences=True)))
    
    model.add(Bidirectional(GRU(32,return_sequences=True)))
    
    model.add(Bidirectional(GRU(32,return_sequences=True)))

    model.add(Bidirectional(GRU(32,return_sequences=True)))

    
    
    model.add(Flatten())

    model.add(Dense(1,activation="sigmoid"))
    optimizer = keras.optimizers.Adam(learning_rate=0.0001,clipnorm=1)
    #model.load_weights("weights.best.hdf5")
    model.compile(optimizer = optimizer,loss ="binary_crossentropy",metrics=["accuracy"])
    model.summary()
    return model

In [127]:
glove_embedded_model =  build_glove_embeddings_text_model(embedding_matrix,vocab=vocab_size,input_length = 100,word_length=50)

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 100, 50)           857100    
_________________________________________________________________
bidirectional_70 (Bidirectio (None, 100, 512)          473088    
_________________________________________________________________
bidirectional_71 (Bidirectio (None, 100, 512)          1182720   
_________________________________________________________________
bidirectional_72 (Bidirectio (None, 100, 256)          493056    
_________________________________________________________________
bidirectional_73 (Bidirectio (None, 100, 256)          296448    
_________________________________________________________________
bidirectional_74 (Bidirectio (None, 100, 256)          296448    
_________________________________________________________________
bidirectional_75 (Bidirectio (None, 100, 128)         

In [ ]:
glove_embedded_model.fit(X_train,y_train,epochs = 30,verbose =1,batch_size = 5,validation_split = 0.1,validation_data=(X_test,y_test),callbacks=[callbacks_list])

Epoch 1/30
960/960 [==============================] - 319s 297ms/step - loss: 0.5056 - accuracy: 0.7748 - val_loss: 0.4660 - val_accuracy: 0.7955

Epoch 00001: val_accuracy did not improve from 0.81801
Epoch 2/30
 73/960 [=>............................] - ETA: 1:07:23 - loss: 0.4981 - accuracy: 0.7890

In [124]:
# evaluate model 
loss, accuracy =glove_embedded_model.evaluate(X_train,y_train,verbose =1)
print("accuracy :%f" %(accuracy*100))

167/167 [==============================] - 9s 54ms/step - loss: 0.3468 - accuracy: 0.8579
accuracy :85.794711


In [125]:
# evaluate model 
loss, accuracy =glove_embedded_model.evaluate(X_test,y_test,verbose =1)
print("accuracy :%f" %(accuracy*100))

72/72 [==============================] - 4s 58ms/step - loss: 0.4771 - accuracy: 0.8021
accuracy :80.210155


In [102]:
predictions = glove_embedded_model.predict(test_padded_docs)

In [103]:
predictions

array([[0.83786625],
       [0.7259326 ],
       [0.733309  ],
       ...,
       [0.43739218],
       [0.4469299 ],
       [0.3787275 ]], dtype=float32)

In [112]:
test_labels = np.where(predictions >= 0.5 ,1,0)

In [113]:
test_labels

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [114]:
sub_file = pd.read_csv("/kaggle/input/nlp-getting-started/sample_submission.csv")

In [115]:
sub_file

id  target
0         0       0
1         2       0
2         3       0
3         9       0
4        11       0
...     ...     ...
3258  10861       0
3259  10865       0
3260  10868       0
3261  10874       0
3262  10875       0

[3263 rows x 2 columns]

In [116]:
sub_file["target"].value_counts()

0    3263
Name: target, dtype: int64

In [117]:
sub_file["target"] = test_labels

In [118]:
sub_file["target"].value_counts()

0    2187
1    1076
Name: target, dtype: int64

In [111]:
sub_file.to_csv("submission3.csv",index=False)

In [41]:
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import LayerNormalization
from keras.callbacks import EarlyStopping

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,Flatten
from tensorflow.keras.layers import Dropout

In [42]:
X_train_total = X_train.copy()


In [43]:
!pip install keras-tuner --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 66.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 69.4 MB/s eta 0:00:00:00:01
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.1.1
    Uninstalling typing_extensions-4.1.1:
      Successfully uninstalled typing_extensions-4.1.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: h5py
    Found existing installation: h5py 3.8.0
    Uninstalling h5py-3.8.0:
      Successfully uninstalled h5py-3.8.0
  Attempting uninstall: keras-tuner
    Found existing installation: keras-tuner 1.1.2
    Uninstalling keras-tuner-1.1.2:
      Successfully uninstalled keras-tuner-1.1.2
ERROR: pip's dependency resolver does not currently take into account all the pa

In [95]:
import keras_tuner 
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import keras_tuner as kt
from tensorflow.keras.losses import binary_crossentropy

from kerastuner import HyperModel


# HyperModel is an abstract class that defines the structure of a model that can be tuned.
# it requires the implementation of a build method, which takes in a HyperParameters object and returns a compiled Keras model. This allows the HyperModel to be customized to the specific requirements of the problem being solved.

from kerastuner import HyperParameters

# HyperParameters is a class that provides an interface for defining hyperparameters for a Keras model. It allows the specification of different types of hyperparameters, such as Int, Float, Choice, etc. 
# It also provides methods for sampling hyperparameters, which are used during the hyperparameter search process.


In [96]:
# creates an instance of the HyperParameters class from the Keras Tuner (kt) library.

# Hyperparameters are variables that are set before training a machine learning model, and can significantly impact its performance. Examples of hyperparameters include learning rate, batch size, number of layers, number of neurons in each layer, regularization coefficients, and activation functions.
hp = kt.HyperParameters()


In [97]:
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
es = EarlyStopping(monitor='accuracy', patience=3)
callbacks_list = [checkpoint, es]

In [98]:


class Tuning(HyperModel):



    def __init__(self, vocab, word_length, input_length,embedding_matrix ,num_classes):
            self.vocab = vocab
            self.word_length = word_length
            self.input_length = input_length
            self.embedding_matrix= embedding_matrix
            self.num_classes = num_classes
           



    def build(self,hp):
        model = keras.Sequential()
        
        model.add(Embedding(
                                input_dim=self.vocab,
                                output_dim=self.word_length,
                                input_length=self.input_length,
                                trainable=False, 
                                weights=[self.embedding_matrix]))        
        
        
        # Tune the number of hidden layers
        for i in range(hp.Int('num_layers', min_value=2, max_value=8)):
            
                    # Add a Bidirectional GRU layer with return_sequences=True
                model.add(Bidirectional(GRU(units=hp.Int('units',
                                                  min_value=128,
                                                  max_value=512,
                                                  step=32),
                                    activation='relu',
                                    return_sequences=True)))
                
                model.add(BatchNormalization())
                # Add dropout regularization
                model.add(layers.Dropout(hp.Float('dropout_' + str(i), min_value=0.0, max_value=0.3, step=0.1)))
                

 




        model.add(Flatten())
    
        # Add a Dense layer
        model.add(Dense(units=self.num_classes-1, activation='sigmoid'))

        # Compile the model
        model.compile(loss='categorical_crossentropy',
                      optimizer=keras.optimizers.Adam(
                          hp.Choice('learning_rate',
                                    values=[1e-3, 1e-2])),
                      metrics=['accuracy'])

        return model


In [99]:
tuning1 = Tuning(vocab=vocab_size,word_length=50,input_length = 100,embedding_matrix=embedding_matrix,num_classes=2) # creating an object for Tuning class


In [100]:
tuning1.build(hp)

In [101]:
from kerastuner.tuners import BayesianOptimization
"""
The arguments to the Hyperband constructor are:

tuning1: an instance of a HyperModel subclass, which defines the machine learning model and its associated hyperparameters that will be tuned by the Hyperband tuner.
objective: an instance of the Objective class from the Keras Tuner library, which specifies the metric to be optimized during the hyperparameter search. In this case, the metric is f1_m, which is a custom metric defined elsewhere in the code.

"""
tuner = kt.BayesianOptimization(
    tuning1,
    objective=kt.Objective('accuracy', direction='max'),
    max_trials = 10
    )


In [ ]:




"""
Hyperband tuner, using the search method. The search method takes several arguments:

X_train_total and y_train: the training data and labels to be used for training and validation during the hyperparameter search.
epochs: the maximum number of epochs to train each model during the hyperparameter search.
validation_split: the fraction of the training data to use for validation during the hyperparameter search.
batch_size: the batch size to use for training and validation during the hyperparameter search, which is sampled from the hyperparameter space defined by the hp.Int method with minimum value 10, maximum value 40, and step 2.
"""
tuner.search(X_train_total, y_train, epochs=2, validation_split=0.2,batch_size=hp.Int('batch_size', min_value=50, max_value=100, step=10),callbacks=[callbacks_list])


Trial 5 Complete [00h 05m 30s]
accuracy: 0.5681445002555847

Best accuracy So Far: 0.6821486949920654
Total elapsed time: 00h 36m 59s

Search: Running Trial #6

Value             |Best Value So Far |Hyperparameter
3                 |7                 |num_layers
384               |128               |units
0.2               |0                 |dropout_0
0.1               |0.2               |dropout_1
0.01              |0.001             |learning_rate
0                 |0.1               |dropout_2
0                 |0.1               |dropout_3
0.2               |0.1               |dropout_4
0                 |0                 |dropout_5
0                 |0                 |dropout_6

Epoch 1/2
26/86 [========>.....................] - ETA: 1:34 - loss: 0.0000e+00 - accuracy: 0.5438