In [6]:
import pandas as pd
import numpy as np

In [7]:
train_df = pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
test_df = pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")

In [8]:
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [9]:
train_df["text"][45]

'I gained 3 followers in the last week. You? Know your stats and grow with http://t.co/TIyUliF5c6'

In [10]:
train_df = train_df.drop(["id","keyword","location"],axis =1)

In [11]:
train_df.head()

text  target
0  Our Deeds are the Reason of this #earthquake M...       1
1             Forest fire near La Ronge Sask. Canada       1
2  All residents asked to 'shelter in place' are ...       1
3  13,000 people receive #wildfires evacuation or...       1
4  Just got sent this photo from Ruby #Alaska as ...       1

In [12]:
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [13]:
test_df = test_df.drop(["id","keyword","location"],axis =1)

In [14]:
test_df.head()

text
0                 Just happened a terrible car crash
1  Heard about #earthquake is different cities, s...
2  there is a forest fire at spot pond, geese are...
3           Apocalypse lighting. #Spokane #wildfires
4      Typhoon Soudelor kills 28 in China and Taiwan

In [15]:
import spacy

nlp = spacy.load("en_core_web_sm")
spacy_stopwords = nlp.Defaults.stop_words

def remove_stopwords(text):
    tokens = nlp(text)
    filtered_tokens = [token.text for token in tokens if not token.is_stop]
    return " ".join(filtered_tokens)

train_df['text'] = train_df['text'].apply(remove_stopwords)
test_df['text'] = test_df['text'].apply(remove_stopwords)


In [16]:
train_df

text  target
0               Deeds Reason # earthquake ALLAH Forgive       1
1               Forest fire near La Ronge Sask . Canada       1
2     residents asked ' shelter place ' notified off...       1
3     13,000 people receive # wildfires evacuation o...       1
4     got sent photo Ruby # Alaska smoke # wildfires...       1
...                                                 ...     ...
7608  giant cranes holding bridge collapse nearby ho...       1
7609  @aria_ahrary @TheTawniest control wild fires C...       1
7610  M1.94 [ 01:04 UTC]?5 km S Volcano Hawaii . htt...       1
7611  Police investigating e - bike collided car Lit...       1
7612  Latest : Homes Razed Northern California Wildf...       1

[7613 rows x 2 columns]

In [17]:
"""import pandas as pd
import nltk
from nltk.tokenize import TweetTokenizer

# Instantiate the tokenizer
tokenizer = TweetTokenizer()

# Define a function to tokenize a tweet
def tokenize_tweet(tweet):
    return tokenizer.tokenize(tweet)

# Apply the function to every row in the DataFrame
train_df['text'] = train_df['text'].apply(tokenize_tweet)
test_df['text'] = test_df['text'].apply(tokenize_tweet)


"""

"import pandas as pd\nimport nltk\nfrom nltk.tokenize import TweetTokenizer\n\n# Instantiate the tokenizer\ntokenizer = TweetTokenizer()\n\n# Define a function to tokenize a tweet\ndef tokenize_tweet(tweet):\n    return tokenizer.tokenize(tweet)\n\n# Apply the function to every row in the DataFrame\ntrain_df['text'] = train_df['text'].apply(tokenize_tweet)\ntest_df['text'] = test_df['text'].apply(tokenize_tweet)\n\n\n"

In [18]:
train_df["text"] = train_df["text"].str.lower()
test_df["text"] = test_df["text"].str.lower()

In [19]:
train_df.head()

text  target
0            deeds reason # earthquake allah forgive       1
1            forest fire near la ronge sask . canada       1
2  residents asked ' shelter place ' notified off...       1
3  13,000 people receive # wildfires evacuation o...       1
4  got sent photo ruby # alaska smoke # wildfires...       1

In [20]:
import re
def remove_html_tags(text):
    pattern = re.compile("<.*?>")
    return pattern .sub(r' ',text )

In [21]:
train_df["text"] = train_df["text"].apply(remove_html_tags)
test_df["text"] = test_df["text"].apply(remove_html_tags)


In [22]:
train_df.sample(10)

text  target
413   # nowplaying arsonist mc -   impressed -   @ar...       0
1217  bradford . best . burning buildings . read wee...       1
4591  @judson1360 @xtra1360 o - line pass rush .   r...       0
1329  days summer supposed fun fun accidentally burn...       0
6401  # isis claims responsibility saudi suicide bom...       1
249   : starmade : : stardate 3 : : planetary annihi...       1
6338  [ clip ] - coercion - structural weakness ensu...       0
2243  @thewesterngaz sure shop deluged local childre...       0
774   watched : honey blew economy \n\n recommend : ...       0
4403  # hot   funtenna : hijacking computers send da...       1

In [23]:

def remove_urls(text):
    pattern = re.compile(r"https?://\S+|www\.\S+")
    return pattern.sub(r'',text)

In [24]:
train_df["text"] = train_df["text"].apply(remove_urls)
test_df["text"] = test_df["text"].apply(remove_urls)


In [25]:
train_df.sample(10)

text  target
5608  latest : homes razed northern california wildf...       1
3728                              fear . taking risks .       1
2427  trains derailed @wmata shut orange / blue dc ?...       1
6864  @arobotlegion . tell oppressed group people re...       0
4395  murderous story america‰ûªs hijacking : earnes...       1
2923  sadly save humanity ursula drowned drool proto...       1
748              @mfalcon21 look . blew w atomic bomb .       0
5969  @justinbieber @arianagrande hear screaming ! !...       0
4948  @tinybaby @adultblackmale @mattytalks meltdown...       1
2100  liked @youtube video @jeromekem  dj hazard - d...       0

In [26]:
train_df["target"].value_counts(normalize = True)

0    0.57034
1    0.42966
Name: target, dtype: float64

In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [28]:
t = Tokenizer(oov_token="UNK")
t.fit_on_texts(train_df["text"]) # create undex for each word sometimes index genearation might be different from others


vocab_size = len(t.word_index)+1 # why should add 1 because when we do padding we will introduce 0 
print(vocab_size)

17142


In [29]:
# integer encode the documents 
encoded_docs = t.texts_to_sequences(train_df["text"]) # transformations of senetences
print(train_df["text"].head())


0              deeds reason # earthquake allah forgive
1              forest fire near la ronge sask . canada
2    residents asked ' shelter place ' notified off...
3    13,000 people receive # wildfires evacuation o...
4    got sent photo ruby # alaska smoke # wildfires...
Name: text, dtype: object


In [30]:
# numerical representation of first sentence
print(encoded_docs[0])

[4306, 691, 135, 1402, 4307]


In [31]:
test_encoded_docs = t.texts_to_sequences(test_df["text"])

In [32]:
max_length = 100
padded_docs = pad_sequences(encoded_docs,maxlen=max_length,padding ="post")
test_padded_docs = pad_sequences(test_encoded_docs,maxlen=max_length,padding ="post")
print(padded_docs)
type(padded_docs)

[[4306  691  135 ...    0    0    0]
 [  85    5  118 ...    0    0    0]
 [1525 1403    2 ...    0    0    0]
 ...
 [2558 2163  552 ...    0    0    0]
 [  14  946  437 ...    0    0    0]
 [ 102   97  406 ...    0    0    0]]


numpy.ndarray

In [33]:
type(train_df["text"])

pandas.core.series.Series

In [34]:
text = np.array(train_df["target"])

In [35]:
X = padded_docs
y = text

In [36]:
test_padded_docs

array([[ 734, 1727,   46, ...,    0,    0,    0],
       [ 340,  135,  998, ...,    0,    0,    0],
       [  85,    5,  653, ...,    0,    0,    0],
       ...,
       [ 784,  527,  224, ...,    0,    0,    0],
       [5971,  450,  301, ...,    0,    0,    0],
       [5662, 2567, 1393, ...,    0,    0,    0]], dtype=int32)

In [37]:
from sklearn.model_selection import train_test_split
  

  

X_train, X_test,y_train, y_test = train_test_split(X,y ,
                                   random_state=10, 
                                   test_size=0.30, 
                                   shuffle=True)

In [38]:
def get_glove_embeddings_from_file(path):
    glove = open(path,"r",encoding = "utf-8")
    glove_dict ={}
    for line in glove:
        values = line.split()
        word =values[0]
        word_vec = np.asarray(values[1:])
        glove_dict[word] = word_vec
    glove.close()
    return glove_dict

In [39]:
#glove_dict = get_glove_embeddings_from_file(path="/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.100d.txt")

In [40]:
#glove_dict1 = get_glove_embeddings_from_file(path="/content/gdrive/MyDrive/glove.6B.200d.txt")

In [41]:
glove_dict2 = get_glove_embeddings_from_file(path="/kaggle/input/glove-global-vectors-for-word-representation/glove.6B.50d.txt")

In [42]:
glove_dict2["the"]

array(['0.418', '0.24968', '-0.41242', '0.1217', '0.34527', '-0.044457',
       '-0.49688', '-0.17862', '-0.00066023', '-0.6566', '0.27843',
       '-0.14767', '-0.55677', '0.14658', '-0.0095095', '0.011658',
       '0.10204', '-0.12792', '-0.8443', '-0.12181', '-0.016801',
       '-0.33279', '-0.1552', '-0.23131', '-0.19181', '-1.8823',
       '-0.76746', '0.099051', '-0.42125', '-0.19526', '4.0071',
       '-0.18594', '-0.52287', '-0.31681', '0.00059213', '0.0074449',
       '0.17778', '-0.15897', '0.012041', '-0.054223', '-0.29871',
       '-0.15749', '-0.34758', '-0.045637', '-0.44251', '0.18785',
       '0.0027849', '-0.18411', '-0.11514', '-0.78581'], dtype='<U11')

In [43]:
def get_glove_embeddings(tokenizer,glove_dict,word_length):
    vocab = len(tokenizer.word_index)+1
    embedding_matrix = np.zeros((vocab,word_length))
    for word , i in tokenizer.word_index.items():
        embedding_vector = glove_dict.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector
    return embedding_matrix

In [44]:
embedding_matrix=get_glove_embeddings(tokenizer = t,glove_dict = glove_dict2,word_length=50)

In [45]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,Flatten,BatchNormalization,LayerNormalization, Bidirectional,Dropout,LSTM,GRU
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from tensorflow import keras


In [77]:
filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')
es = EarlyStopping(monitor='val_accuracy', patience=3)
callbacks_list = [checkpoint, es]

In [78]:
def build_glove_embeddings_text_model(embedding_matrix,vocab,input_length,word_length):
    model = Sequential()
    model.add(Embedding(vocab,word_length,input_length=input_length,weights=[embedding_matrix],trainable =False))
    
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))
    model.add(Dropout(0.1))
    model.add(Bidirectional(GRU(128,return_sequences=True)))

    
    
    model.add(Flatten())

    model.add(Dense(1,activation="sigmoid"))
    optimizer = keras.optimizers.Adam(learning_rate=0.0001,clipnorm=1)
    #model.load_weights("weights.best.hdf5")
    model.compile(optimizer = optimizer,loss ="binary_crossentropy",metrics=["accuracy"])
    model.summary()
    return model

In [79]:
glove_embedded_model =  build_glove_embeddings_text_model(embedding_matrix,vocab=vocab_size,input_length = 100,word_length=50)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 100, 50)           857100    
_________________________________________________________________
bidirectional_45 (Bidirectio (None, 100, 256)          138240    
_________________________________________________________________
dropout (Dropout)            (None, 100, 256)          0         
_________________________________________________________________
bidirectional_46 (Bidirectio (None, 100, 256)          296448    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100, 256)          0         
_________________________________________________________________
bidirectional_47 (Bidirectio (None, 100, 256)          296448    
_________________________________________________________________
dropout_2 (Dropout)          (None, 100, 256)         

In [84]:
glove_embedded_model.fit(X_train,y_train,epochs = 10,verbose =1,batch_size = 5,validation_split = 0.2,validation_data=(X_train,y_train),callbacks=[callbacks_list])

Epoch 1/10
1066/1066 [==============================] - 155s 145ms/step - loss: 0.4461 - accuracy: 0.8000 - val_loss: 0.4413 - val_accuracy: 0.8039

Epoch 00001: saving model to weights.best.hdf5
Epoch 2/10
1066/1066 [==============================] - 155s 145ms/step - loss: 0.4384 - accuracy: 0.8099 - val_loss: 0.4531 - val_accuracy: 0.8047

Epoch 00002: saving model to weights.best.hdf5
Epoch 3/10
1066/1066 [==============================] - 156s 146ms/step - loss: 0.4291 - accuracy: 0.8138 - val_loss: 0.4432 - val_accuracy: 0.8082

Epoch 00003: saving model to weights.best.hdf5
Epoch 4/10
1066/1066 [==============================] - 155s 145ms/step - loss: 0.4224 - accuracy: 0.8185 - val_loss: 0.4339 - val_accuracy: 0.8074

Epoch 00004: saving model to weights.best.hdf5
Epoch 5/10
1066/1066 [==============================] - 154s 145ms/step - loss: 0.4147 - accuracy: 0.8215 - val_loss: 0.4491 - val_accuracy: 0.8030

Epoch 00005: saving model to weights.best.hdf5
Epoch 6/10
1066/1066

In [85]:
# evaluate model 
loss, accuracy =glove_embedded_model.evaluate(X_train,y_train,verbose =1)
print("accuracy :%f" %(accuracy*100))

167/167 [==============================] - 9s 53ms/step - loss: 0.3628 - accuracy: 0.8467
accuracy :84.668791


In [86]:
# evaluate model 
loss, accuracy =glove_embedded_model.evaluate(X_test,y_test,verbose =1)
print("accuracy :%f" %(accuracy*100))

72/72 [==============================] - 4s 50ms/step - loss: 0.4510 - accuracy: 0.8109
accuracy :81.085813


In [87]:
predictions = glove_embedded_model.predict(test_padded_docs)

In [88]:
predictions

array([[0.80920273],
       [0.8111965 ],
       [0.68930495],
       ...,
       [0.7669214 ],
       [0.46929905],
       [0.78231895]], dtype=float32)

In [89]:
test_labels = np.where(predictions >= 0.5 ,1,0)

In [90]:
test_labels

array([[1],
       [1],
       [1],
       ...,
       [1],
       [0],
       [1]])

In [91]:
sub_file = pd.read_csv("/kaggle/input/nlp-getting-started/sample_submission.csv")

In [92]:
sub_file

id  target
0         0       0
1         2       0
2         3       0
3         9       0
4        11       0
...     ...     ...
3258  10861       0
3259  10865       0
3260  10868       0
3261  10874       0
3262  10875       0

[3263 rows x 2 columns]

In [93]:
sub_file["target"] = test_labels

In [94]:
sub_file

id  target
0         0       1
1         2       1
2         3       1
3         9       1
4        11       1
...     ...     ...
3258  10861       1
3259  10865       1
3260  10868       1
3261  10874       0
3262  10875       1

[3263 rows x 2 columns]

In [95]:
sub_file.to_csv("submission.csv",index=False)